# SITE CONFIGURATION
baseurl: "" # the subpath of your site, e.g. /blog/
url: "www.barkmin.eu" # the base hostname & protocol for your site

# THEME-SPECIFIC CONFIGURATION
theme:
  # Meta
  title: Mike Barkmin
  avatar: avatar.png
  gravatar: # Email MD5 hash
  description: "A website with blog posts and pages" # used by search engines

  # Header and footer text
  header_text:
  footer_text: >
   Copyright © 2015 | <a href="/impressum/">Impressum</a>

  # Icons
  rss: false
  email_address: mike@barkmin.eu # Full email address, e.g. "sam@example.com"
  behance:
  bitbucket: mikescho
  dribbble:
  facebook:
  flickr:
  github: mikescho
  google_plus:
  instagram: mikebarkmin
  linkedin:  # Full URL
  pinterest:
  reddit:
  soundcloud:
  stack_exchange:  # Full URL
  steam:
  tumblr:
  twitter: MikeBarkmin
  wordpress:
  youtube: MikeBarkmin

  # Scripts
  google_analytics: # Tracking ID, e.g. "UA-000000-01"
  disqus_shortname:
  katex: true # Enable if using math markup

  # Localization strings
  str_follow_on: "Follow on"
  str_rss_follow: "Follow RSS feed"
  str_email: "Email"
  str_next: "Nächster"
  str_prev: "Vorheriger"
  str_continue_reading: "Weiterlesen"

  # Colours, typography and padding
  # Open the "_sass > base" folder, and open "_variables.scss"



# BUILD SETTINGS
markdown: kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: :compressed
